# Generated by Django 2.1.7 on 2019-02-26 07:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_engine_no', models.CharField(max_length=100)),
                ('car_registration_no', models.CharField(max_length=100)),
                ('car_consumption_rate', models.CharField(max_length=100)),
                ('car_image', models.ImageField(upload_to='')),
                ('availability', models.CharField(default='AVAILABLE', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 560532, tzinfo=utc))),
                ('complaint', models.TextField(max_length=500)),
                ('other_complainant', models.CharField(blank=True, max_length=100, null=True)),
                ('forwarded_status', models.CharField(default='NOT FORWARDED', max_length=100)),
                ('handled_status', models.CharField(default='NOT HANDLED', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_next_of_kin', models.CharField(max_length=100)),
                ('driver_next_of_kin_contact', models.CharField(max_length=100)),
                ('next_of_kin_national_id_image', models.ImageField(upload_to='')),
                ('driver_licence_no', models.CharField(max_length=100)),
                ('driver_contact', models.CharField(max_length=100)),
                ('driver_email', models.EmailField(max_length=100)),
                ('driver_image', models.ImageField(upload_to='')),
                ('driver_monthly_payment', models.FloatField(default=1133600.0)),
                ('driver_permit_or_nationalID_image', models.ImageField(upload_to='')),
                ('driver_monthly_payment_ref', models.FloatField(default=0.0)),
                ('attached_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonapp.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Driver_Payment_Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 561624, tzinfo=utc))),
                ('driver_name', models.CharField(default='name', max_length=100, null=True)),
                ('driver_car', models.CharField(default='car', max_length=100, null=True)),
                ('amount_paid', models.FloatField(default=0.0, null=True)),
                ('balance', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_payment_Reports_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 562488, tzinfo=utc))),
                ('driver_name', models.CharField(default='name', max_length=100, null=True)),
                ('driver_car', models.CharField(default='car', max_length=100, null=True)),
                ('amount_paid', models.FloatField(default=0.0, null=True)),
                ('balance', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 561145, tzinfo=utc))),
                ('paid_amount', models.FloatField(default=0.0)),
                ('paid_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayments_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 562019, tzinfo=utc))),
                ('paid_amount', models.FloatField(default=0.0)),
                ('paid_by', models.CharField(max_length=100)),
                ('received_by', models.CharField(max_length=100)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_image')),
                ('username', models.CharField(default='', max_length=20)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default='')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=250)),
                ('role_title', models.CharField(choices=[('', ''), ('Executive', 'Executive'), ('Manager', 'Manager'), ('Admin', 'Admin'), ('Receptionist', 'Receptionist'), ('Accountant', 'Accountant'), ('Operations', 'Operations')], default='', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('role_logo', models.ImageField(upload_to='profile_image')),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 563351, tzinfo=utc))),
                ('Salary_Type', models.CharField(choices=[('ALLOWANCE', 'Pay Allowances'), ('Salary', 'Monthly Salary'), ('Advance', 'Pay Advances'), ('Commission', 'Pay Commission')], default='SALARY', max_length=12)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Month of Pay', max_length=12)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.TextField(default='amount in words', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 564291, tzinfo=utc))),
                ('PaymentMadeTo', models.CharField(default='Canon', max_length=100)),
                ('ReasonForPayment', models.CharField(choices=[('Mechanic', 'Car Repairing'), ('WaterBills', 'Water Bills'), ('Electricity', 'Electricity Bills'), ('URA', 'Paying Revenue')], max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.TextField(default='amount in words', max_length=500)),
                ('ReceivedBy', models.CharField(default='Receiptionist', max_length=100)),
                ('ApprovedBy', models.CharField(default='Manager', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FistName', models.CharField(default='1st name', max_length=150)),
                ('SecondName', models.CharField(default='2nd name', max_length=150)),
                ('Salary', models.IntegerField(default=0)),
                ('Role', models.CharField(choices=[('Developers', 'ICT'), ('Receptionist', 'Rec'), ('Director', 'DIR'), ('Operations', 'CEO'), ('Cashiers', 'Cashier'), ('Executive', 'Exe')], default='MALE', max_length=20)),
                ('Duties', models.TextField(default='ICT', max_length=1000)),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='MALE', max_length=7)),
                ('Contact', models.CharField(default='Tel or Email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 26, 7, 39, 41, 563909, tzinfo=utc))),
                ('PaymentMadeTo', models.CharField(default='Canon', max_length=100)),
                ('ReasonForPayment', models.TextField(default='Only relatively small expense', max_length=25)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.TextField(default='amount in words', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonapp.StaffDetails'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canonapp.Role'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canonapp.Driver'),
        ),
    ]
