# Generated by Django 2.1.7 on 2019-03-01 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('canonapp', '0002_auto_20190227_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AddField(
            model_name='driver_payment_reports_archive',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver_payment_reports_archive',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverpayments_archive',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverpayments_archive',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='canonapp.Driver'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 11065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='attached_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canonapp.Car'),
        ),
        migrations.AlterField(
            model_name='driver_payment_report',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 12009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver_payment_reports_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 12947, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 11559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayment',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canonapp.Driver'),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 12436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driverpayments_archive',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canonapp.Driver'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 13864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='canonapp.StaffDetails'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 14732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 17, 3, 46, 14354, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
