# Generated by Django 2.1.7 on 2019-02-27 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('', ''), ('Executive', 'Executive'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Accountant', 'Accountant'), ('Operations', 'Operations')], default='', max_length=20)),
                ('phone', models.IntegerField(default='+256701345376')),
                ('hired_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
